# backend/ai_module.py

import google.generativeai as genai

# --- PASTE YOUR GEMINI API KEY HERE ---
GEMINI_API_KEY = "AIzaSyBBHVjQ4xtP6ZtghkLFaleZb-t3WFfH4oQ"

# --- CONFIGURE THE GEMINI LIBRARY ---
try:
    genai.configure(api_key=GEMINI_API_KEY)
    print("SUCCESS: Google AI SDK configured successfully.")
except Exception as e:
    print(f"ERROR: Failed to configure Google AI SDK. Reason: {e}")


# We will create our resume generation function here later.
# For now, this file just sets up the connection.
def generate_resume_content(user_profile, job_description):
    # This is a placeholder for now.
    print("AI module called to generate resume content.")
    return "This is a placeholder resume generated by the AI module."