# backend/services/report_builder.py
"""
Rule-based report builder used when LLM report generation fails.
Produces overall_score, dimensions, strengths, weaknesses, quick_wins, transcript.
"""

from typing import Dict, Any, List
from statistics import mean

def build_report_rule_based(session: Dict) -> Dict:
    history = session.get("history", [])
    scores = []
    strengths = []
    weaknesses = []
    transcript = []

    for ex in history:
        evalr = ex.get("evaluation") or {}
        score = int(evalr.get("score", 0))
        scores.append(score)
        # collect strengths/weaknesses
        strengths.extend(evalr.get("strengths", []) or [])
        weaknesses.extend(evalr.get("weaknesses", []) or [])
        transcript.append({
            "question": ex.get("question_text"),
            "user_answer": ex.get("user_answer"),
            "feedback": evalr.get("feedback"),
            "improved_answer": ex.get("improved_answer")
        })

    overall = int(mean(scores)) if scores else 0

    # crude dimensional splits based on metrics if available (communication, technical_depth, structure, confidence)
    comm = int(min(100, overall + 5))
    technical = int(max(0, overall - 5))
    structure = int(min(100, overall))
    confidence = int(min(100, overall - 3))

    # quick wins: extract first few weaknesses into actionable lines
    quick_wins = []
    for w in weaknesses[:6]:
        quick_wins.append({"title": "Improve answer", "description": str(w)})

    # dedupe strengths
    def dedupe(seq: List[str]) -> List[str]:
        out = []
        seen = set()
        for s in seq:
            if not s: continue
            k = s.lower().strip()
            if k not in seen:
                seen.add(k)
                out.append(s)
        return out

    return {
        "overall_score": overall,
        "dimensions": {
            "communication": comm,
            "technical_depth": technical,
            "structure": structure,
            "confidence": confidence
        },
        "strengths": dedupe(strengths),
        "weaknesses": dedupe(weaknesses),
        "quick_wins": quick_wins,
        "transcript": transcript,
        "notes": "Report generated by deterministic fallback. Replace with LLM-generated report when available."
    }
